### ISSUE TITLE
Terminal auto closes after execution, making it impossible to read the error and try to understand what went wrong

### ISSUE THREAD

**Issue by Cobran53** [marcb152/msft-rewards-bot#1]
All is said in the title.
They should be the "pause" command at the end of the batch file, but adding it myself didn't work.

They may be another underlying problem, but I can't read it right now, so... :p

**Comment by marcb152** [comment]
Hi, I added the 'PAUSE' command on a new line in the batch file to see the error and it worked for me (at least the console didn't close itself). Are you sure you saved the batch file after editing it?

You were right about there being an underlying problem.
Some packages files were missing (pyinstaller missed them while compiling), I added them as "additionnal dependencies" in pyinstaller and now everything seems to work fine.
Regarding the 'pause' command, I changed my documentation to mention it in case a problem occurs.

As this issue concerns the terminal closing itself despite the 'pause' command, I will wait for your feeback on the new version before closing this issue thread.

Thank you!
